name: CatSeedLogin
main: cc.baka9.catseedlogin.CatSeedLogin
author: CatSeed
version: 1.0.1
api-version: 1.13
commands:
  login:
    description: 使用密码登录
    usage: /<command> 密码
    aliases: [l]
  register:
    description: 注册密码
    usage: /<command> 密码 重复密码
    aliases: [reg]
  bindemail:
    description: 绑定邮箱,重置密码
    usage:
      |
      /<command> email set 邮箱
      /<command> email verify 验证码
    aliases: [bdmail]
  changepassword:
    description: 修改密码
    usage: /<command> 旧密码 新密码 重复新密码
    aliases: [changepw]
  adminsetpassword:
    description: 管理员强制设置玩家密码
    usage: /<command> 玩家名 密码
    aliases: [adminsetpw]
    permission: catseedlogin.command.adminsetpassword