IpRegisterCountLimit: 2
IpCountLimit: 2
LimitChineseID: true
MinLengthID: 2
MaxLengthID: 15
BeforeLoginNoDamage: true
ReenterInterval: 60
AfterLoginBack: true
CanTpSpawnLocation: true
CommandWhiteList:
  - /(?i)l(ogin)?(\z| .*)
  - /(?i)reg(ister)?(\z| .*)
  - /(?i)resetpassword?(\z| .*)
  - /(?i)repw?(\z| .*)
  - /(?i)worldedit cui
  - /(?i)vote?(\z| .*)
  - /(?i)i?(\z| .*)
  - /(?i)bindemail(\z| .*)
  - /(?i)bdmail(\z| .*)
  - /(?i)binduuid(\z| .*)
  - /(?i)bdid(\z| .*)
  - /(?i)adduuid(\z| .*)
  - /(?i)addid(\z| .*)

CatSeedLogin-master:
  jar:AutoKick: 120
DeathStateQuitRecordLocation: true
IpWhitelist:
  - 127.0.0.1